[package]
name = "rust_answers"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
day1 = { path = "crates/day1"}
day2 = { path = "crates/day2"}